# .goreleaser.yml

# General customization
project_name: motionerd

# Build customization
builds:
  -
    # Name of the binary
    binary: motionerd

    # Platforms to build
    goos:
      - windows
      - darwin
      - linux

    # Architectures to build
    goarch:
      - 386
      - amd64
    
    # Combinations of platforms and architectures to ignore
    ignore:
      - goos: darwin
        goarch: 386
      #- goos: windows
      #- goos: linux

# Archive customization
archive:
  # Archive format
  format: tar.gz

  # Archive format customization
  format_overrides:
    - goos: windows
      format: zip

  # Archive name customization
  replacements:
    386: 32-bit
    amd64: 64-bit
    windows: Windows
    darwin: macOS
    linux: Linux
  files:
    - README.md
    - LICENSE.txt
    - CHANGELOG.md

# Release customization
release:
  # Release repository
  github:
    owner: Didstopia
    name: motionerd

  # Release automatically (set to false for automatic release)
  draft: true

## TODO: Add homebrew release support?